sudo: required
services:
  - docker

before_install:
  - docker build -t rkshjoshi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rkshjoshi/react-test npm run test

after_success:
  - docker build -t rakeshjoshi/multi-client ./client
  - docker build -t rakeshjoshi/multi-nginx ./nginx
  - docker build -t rakeshjoshi/multi-worker ./worker
  - docker build -t rakeshijoshi/multi-server ./server

# define docker login with environment  variable of travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -password-stdin

#build images and push it to docker hub

  - docker push rakeshjoshi/multi-client
  - docker push rakeshjoshi/multi-nginx
  - docker push rakeshjoshi/multi-worker
  - docker pus rakeshjoshi/multi-server


